### ISSUE TITLE
Error on hover

### ISSUE THREAD

**Issue by zswanson** [VSChina/vscode-ansible#75] opened 2018-02-19 14:05 UTC
Using VS Code 1.20.1
Using vscode-ansible v0.1.3
Running in Windows 7 64bit
No other extensions installed, this is a first-time/fresh install of vscode.

Extension works fine for syntax highlighting and snippet insertion, suggestions. However anytime I hover over an ansible keyword the following error appears in the VS Code console:

> [Error - 9:02:19 AM] Request textDocument/hover failed.
>   Message: Request textDocument/hover failed with message: Cannot read property 'push' of undefined
>  Code: -32603 

It's reported as coming from the "Ansible Playbook Language Server"
[e] Using the developer tool this additional error info is displayed in the console:
> 2log.ts:171   ERR Cannot read property 'element' of undefined: TypeError: Cannot read property 'element' of undefined
    at e.element (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:383:327)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:410:523
    at Array.map (native)
    at e.open (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:410:493)
    at e.onMouseDown (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:400:356)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:849
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:622
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:161:76)
    at HTMLDivElement.r (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:169:105)

**Comment by yaweiw** [comment] 2018-02-20 08:51
@yungez

**Comment by yungez** [comment] 2018-02-23 04:27
Duplicate of #63 

fix is merged already, will release soon.

**Comment by yungez** [comment] 2018-02-24 02:33
fix of the issue is released in latest version 0.1.4. pls have a try and let us know if any further question.

**Closed by yungez** 2018-02-24 02:33 UTC

**Comment by zswanson** [comment] 2018-02-28 13:42
error on hover seems resolved, but I'm also not seeing the actual hover tooltips in 0.1.4 after updating today.

**Comment by yungez** [comment] 2018-03-01 03:04
@zswanson  thanks for the feedback!  one possible reason, hover tooltip over module name will failed to show when yaml file format error, like extra/miss whitespace etc.

**Comment by zswanson** [comment] 2018-03-01 13:07
@yungez I found the cause of discrepancy! It appears that the hover based tooltips only work for 'all in one' playbooks and not Roles, which I'm using at the office. I can open a new enhancement request for that?

**Comment by yaweiw** [comment] 2018-03-02 01:51
@zswanson thanks. Please log an issue and we will prioritize the pipeline.
