### ISSUE TITLE
Errors in output windows when editing ansible .yml files (Unhandled method textDocument/completion, code -32601)

### ISSUE THREAD

**Issue by fessmage** [VSChina/vscode-ansible#179] opened 2018-09-14 14:24 UTC
## Environment
- Extension version: 0.4.0
- OS Type: Ubuntu 18.04.1 x64
- VS Code version: 1.27.1

## Summary
Today whenewer i start writing or editing ansible's yaml files in vscode i instantly get error in output windows of vscode:
[Error - 5:11:03 PM] Request textDocument/completion failed.
  Message: Unhandled method textDocument/completion
  Code: -32601 

## Reproduce steps
Install vscode-ansible 0.4.0 to vscode and write just some letter in empty .yml file with enabled 'ansible' language mode.

## Expected Results
Work without errors in output.

## Actual Results
Repeatedly errors "Unhandled method textDocument/completion", code 32601. Even after setting in vscode "ansible.autocompletion": false and "ansible.validation": false.

**Comment by daledude** [comment] 2018-09-14 16:39
I'm also getting these errors.

**Comment by yungezz** [comment] 2018-09-17 01:45
Thanks for reporting the issue, we've noticed  same error, it seems introduced by some dependency language feature, looking at it.

**Comment by fessmage** [comment] 2018-09-17 12:03
I Updated vscode today to 1.27.2 and see no more errors in .yml files with vscode-ansible plugin. Seems, errors resolved.

**Comment by yungezz** [comment] 2018-09-18 01:59
thanks for sharing this. Nice to see it's resolved.

**Comment by matrixraven** [comment] 2018-09-19 00:43
> I updated vscode today to 1.27.2 and saw no more errors in .yml files with vscode-ansible plugin. Seems, errors resolved.

Not here. Still broken for me. 1.27.2 on Mac.

**Comment by matosc15** [comment] 2018-09-19 01:36
> > I updated vscode today to 1.27.2 and saw no more errors in .yml files with vscode-ansible plugin. Seems, errors resolved.
> 
> Not here. Still broken for me. 1.27.2 on Mac.

Same here. Still experiencing the same issue on both Windows 10 and Linux with 1.27.2.

**Comment by fessmage** [comment] 2018-09-20 12:39
Got this one once again today.

**Comment by yungezz** [comment] 2018-09-21 01:26
the error message is caused by [yaml-language-server](https://github.com/redhat-developer/yaml-language-server) used by language server as dependency. That language server has its own completion provider, it will send the error message to client,  since the yaml langauge server hasn't switch to turn off its  autocompletion now, i did workaround to ignore this errors. The fix will be released in next version.

**Closed** 2018-09-21 08:57 UTC
