### ISSUE TITLE
"Copying workspace to remote host" is unreliable on Windows

### ISSUE THREAD

**Issue by FlorianWagnerZEB** [VSChina/vscode-ansible#156] opened 2018-08-24 07:44 UTC
## Environment
- Extension version: 0.3.1
- OS Type: Windows 7 Enterprise Service Pack 1

## Summary
"Copying workspace to remote host" works only immediately after answering the dialog "Copy workspace to remote host" with "always". After rebooting the system, the feature doesn't work anymore.

## Reproduce steps
1) Clear .vscode/settings.json in workspace folder
2) right click an ansible playbook which has to be executed -> "Run ansible playbook remotely via ssh"
3) Answer the "Copy workspace to remote host" dialog with "always"
4) Everything works fine.
5) Reboot the system
6) Start VSCode
7) make any change in the playbook (and save)
8) right click the playbook -> "Run ansible playbook remotely via ssh"

## Expected Results
the results/output from the updated playbook

## Actual Results
the same results/output as in step 4 since the file was not uploaded to the remote host after the change.

**Comment by yungezz** [comment] 2018-08-27 01:53
@FlorianWagnerZEB thanks for reporting the issue. After you reboot the system, what's expected behavior? you'd like the whole workspace been copied to remote machine immediately when the extension activated? Original design is that: once user changed the remote copying setting, whole workspace will be copied. after  that, only changed files will be copied to remotely. After vscode restarted, only changed files are copied also.

**Comment by bbung** [comment] 2018-08-28 07:57
Hi, 

it could be the following problem. The file is only updated if a session is already established and after reboot this is not the case, so no update is done.

But i think the main problem here is that, changed files are not copied reliably or new files that are not created within vscode are not added/copied at all. We need a check for differences in files and folders every time, bevor executing the playbook.

I can also reproduce this without any rebooting. For example:

1. Create a playbook that uses a template file
2. add or change the template file from **without** vscode
3. run the playbook

Expected Result:
Difference in files will be recognized and files will be updated.

Actual Result:
Playbook will fail with missing template file.

In this case it would work to just change the remote dir or remove the copyOnSave entry from the settings, because the issue is obivous, but if you do more subtle changes to a file and this is not copies correctly it can drive you nuts searching for the issue.

cheers,
Björn

**Comment by yungezz** [comment] 2018-08-31 07:10
Scenarios on file copying:
- A user added a new `FileCopyConfig` in vscode, then  whole workspace will be copied. Because this extension listening to config change notification.
- then user edited some files, those changed files will be copied. Because this extension listening to file change notification.
- user exit vscode,  add/delete some files in whole space.
- user open vscode, and want to see those added/deleted files on remote host.  user need trigger ` Copy folder to remote host` command on demand. Because vscode has no idea about: weather local workspace changed; weather remote workspace changed(extra files have been updated on remote host  by others). So in this scenario, we suggest user do on demand file syncing.

This is really good discussion. It helps us understand user scenarios better. Feel free to share your thoughts and ideas. Thanks.

**Comment by yungezz** [comment] 2018-09-21 08:59
#149

**Comment by yungezz** [comment] 2018-09-26 21:58
close this as duplicate of Issue #149 , this will be a new feature request.

**Closed by yungezz** 2018-09-26 21:58 UTC
Labels: feature-request
